optimize
mycolorway/qing-sortable pull request #1
Opened 2016-10-29 14:09 UTC by ichord

2016-10-29 17:07 UTC, farthinker requested changes

2016-10-29 17:07 UTC, farthinker commented on src/qing-sortable.coffee
> +    @trigger "before-insert-item", [@activeItem]
这个事件应该是多余的，sortend足够用了

2016-10-29 17:07 UTC, farthinker commented on src/qing-sortable.coffee
> +    @trigger 'generate-placeholder', [@placeholder]
如果要自定义placeholder最好增加一个placeholder option，值是一个callback函数

2016-10-29 17:11 UTC, farthinker requested changes

2016-10-29 17:11 UTC, farthinker commented on src/qing-sortable.coffee
> +  @excluded: '[data-qing-sortable-excluded]'
这个类变量之前方应杭写的有点奇怪，其实是多余的，可以顺便改一下，把它去掉
后面cacheDimension的时候只需要直接排除.qing-sortable-helper就可以了

2016-10-30 03:14 UTC, ichord commented on src/qing-sortable.coffee
> +    @trigger 'generate-placeholder', [@placeholder]
这个事件也是为了加防止自动初始化的 `attr` 的，其实没有有必要，去掉了。

2016-10-30 07:28 UTC, farthinker approved these changes

2016-10-30 07:28 UTC, merged